---
title: "plot_introns"
output: html_document
---

```{r setup}
library(ggplot2)
library(plotly)
```

```{r}
df <- read.delim(file = "/Users/chanfreaulab/Documents/GitHub/R_COMPASS_filtering/merged_compass_datasets/full_upf1_rrp6", sep = "" ,header = TRUE, stringsAsFactors = FALSE)
df$U_R_1YPD_spliced_to_unspliced_ratio <- as.numeric(df$U_R_1YPD_spliced_to_unspliced_ratio)
df$U_R_1YPD_spliced_to_unspliced_ratio[is.na(df$U_R_1YPD_spliced_to_unspliced_ratio)] <- 0

df$UPF1_1_YPD_spliced_to_unspliced_ratio <- as.numeric(df$UPF1_1_YPD_spliced_to_unspliced_ratio)
df$UPF1_1_YPD_spliced_to_unspliced_ratio[is.na(df$UPF1_1_YPD_spliced_to_unspliced_ratio)] <- 0

df$U_R_1YPD_bbmap_counts <- as.numeric(df$U_R_1YPD_bbmap_counts)
df$U_R_1YPD_bbmap_counts[is.na(df$U_R_1YPD_bbmap_counts)] <- 0

df$UPF1_1_YPD_bbmap_counts <- as.numeric(df$UPF1_1_YPD_bbmap_counts)
df$UPF1_1_YPD_bbmap_counts[is.na(df$UPF1_1_YPD_bbmap_counts)] <- 0
df$U_R_1YPD_HISAT2_default_counts <- as.numeric(df$U_R_1YPD_HISAT2_default_counts)
df$U_R_1YPD_HISAT2_default_counts[is.na(df$U_R_1YPD_HISAT2_default_counts)] <- 0
```

```{r}
bbmap_plot <- ggplot(data = df)+
  geom_point(aes(x = U_R_1YPD_bbmap_counts, y = UPF1_1_YPD_bbmap_counts, color = V37))+
  scale_x_log10()+
  scale_y_log10()+
  geom_abline(slope = 1)+
  xlab(label = "upf1∆ rrp6∆ bbmap counts")+
  ylab(label = "rrp6∆ bbmap counts")+
  ggtitle("bbmap counts for upf1∆ rrp6∆ vs rrp6∆", subtitle = "Color: Has YTRAY branch point?")
```

```{r}
ggplot(data = df)+
  geom_point(aes(x = U_R_1YPD_bbmap_counts, y = U_R_1YPD_HISAT2_default_counts, color = V37))+
  scale_x_log10()+
  scale_y_log10()+
  geom_abline(slope = 1)+
  xlab(label = "upf1∆ rrp6∆ bbmap counts")+
  ylab(label = "upf1∆ rrp6∆ HISAT2 counts")+
  ggtitle("bbmap vs HISAT for upf1∆ rrp6∆")
```

```{r}
ggplot(data = df)+
  geom_point(aes(x = U_R_1YPD_bbmap_counts, y = UPF1_1_YPD_bbmap_counts, color = V37))+
  scale_x_log10()+
  scale_y_log10()+
  geom_hline(yintercept = 1)+
  geom_vline(xintercept = 1)+
  geom_abline(slope = 1)
```

